# Generated by Django 5.2 on 2025-06-29 04:17
# Django 5.2에 의해 2025-06-29 04:17에 자동 생성됨

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """사용자 승인 시스템 및 역할 관리 필드 추가 (approved_at, approved_by, role, google_id)"""

    dependencies = [
        ("labeling", "0001_initial"),  # 초기 마이그레이션에 의존
    ]

    operations = [
        # 사용자 승인 시간 필드 추가
        migrations.AddField(
            model_name="user",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),  # 승인된 시간 (비어있을 수 있음)
        ),
        
        # 사용자 승인자 필드 추가
        migrations.AddField(
            model_name="user",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,  # 승인자가 삭제되어도 사용자는 유지
                to=settings.AUTH_USER_MODEL,
            ),  # 승인한 관리자 (다른 사용자와 연결)
        ),
        
        # Google ID 필드 추가
        migrations.AddField(
            model_name="user",
            name="google_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),  # Google 계정 ID (고유값)
        ),
        
        # 사용자 역할 필드 추가
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("user", "사용자"), ("admin", "관리자")],  # 역할 선택지
                default="user",  # 기본값은 일반 사용자
                max_length=10,
            ),  # 사용자 역할 (사용자/관리자)
        ),
    ]
