# Generated by Django 5.2 on 2025-06-29 05:32
# Django 5.2에 의해 2025-06-29 05:32에 자동 생성됨

from django.db import migrations, models


class Migration(migrations.Migration):
    """배치 관리 기능 강화 - 생성 시간 추적 및 활성/비활성 상태 관리 (created_at, is_active)"""

    dependencies = [
        ("labeling", "0002_user_approved_at_user_approved_by_user_google_id_and_more"),  # 이전 마이그레이션에 의존
    ]

    operations = [
        # 배치 생성 시간 필드 추가
        migrations.AddField(
            model_name="batch",
            name="created_at",
            field=models.DateTimeField(blank=True, null=True),  # 배치가 생성된 시간 (비어있을 수 있음)
        ),
        
        # 배치 활성 상태 필드 추가
        migrations.AddField(
            model_name="batch",
            name="is_active",
            field=models.BooleanField(default=True),  # 배치 활성화 여부 (기본값: 활성)
        ),
    ]
