# Generated by Django 5.2 on 2025-06-29 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labeling", "0002_user_approved_at_user_approved_by_user_google_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="batch",
            name="created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="batch",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
