# Generated by Django 5.2 on 2025-06-29 06:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labeling", "0003_batch_created_at_batch_is_active"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="labelingresult",
            unique_together={("user", "image")},
        ),
        migrations.CreateModel(
            name="ImageAccessLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_file_id", models.CharField(max_length=200)),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField(blank=True)),
                ("access_time", models.DateTimeField(auto_now_add=True)),
                ("success", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-access_time"],
                "indexes": [
                    models.Index(
                        fields=["user", "access_time"],
                        name="labeling_im_user_id_19efad_idx",
                    ),
                    models.Index(
                        fields=["image_file_id", "access_time"],
                        name="labeling_im_image_f_724b6f_idx",
                    ),
                    models.Index(
                        fields=["ip_address", "access_time"],
                        name="labeling_im_ip_addr_2ce8fd_idx",
                    ),
                ],
            },
        ),
    ]
