# Generated by Django 5.2 on 2025-06-29 06:17
# Django 5.2에 의해 2025-06-29 06:17에 자동 생성됨

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """라벨링 데이터 무결성 보장 및 보안 모니터링 시스템 추가 (고유 제약조건, ImageAccessLog)"""

    dependencies = [
        ("labeling", "0003_batch_created_at_batch_is_active"),  # 이전 마이그레이션에 의존
    ]

    operations = [
        # 라벨링 결과에 고유 제약 조건 추가 (한 사용자가 한 이미지에 대해 하나의 결과만 가질 수 있음)
        migrations.AlterUniqueTogether(
            name="labelingresult",
            unique_together={("user", "image")},  # 사용자와 이미지 조합이 고유해야 함
        ),
        
        # 이미지 접근 로그 모델 생성 - 이미지 접근 추적 및 보안 모니터링
        migrations.CreateModel(
            name="ImageAccessLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_file_id", models.CharField(max_length=200)),  # 이미지 파일 ID
                ("ip_address", models.GenericIPAddressField()),  # 접근한 IP 주소
                ("user_agent", models.TextField(blank=True)),  # 사용자 브라우저 정보
                ("access_time", models.DateTimeField(auto_now_add=True)),  # 접근 시간 (자동 기록)
                ("success", models.BooleanField(default=True)),  # 접근 성공 여부
                ("error_message", models.TextField(blank=True)),  # 오류 메시지 (접근 실패 시)
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),  # 접근한 사용자 (사용자 삭제 시 로그도 삭제)
                ),
            ],
            options={
                "ordering": ["-access_time"],  # 접근 시간 역순으로 정렬 (최신순)
                "indexes": [
                    # 사용자별 접근 시간 인덱스
                    models.Index(
                        fields=["user", "access_time"],
                        name="labeling_im_user_id_19efad_idx",
                    ),
                    # 이미지별 접근 시간 인덱스
                    models.Index(
                        fields=["image_file_id", "access_time"],
                        name="labeling_im_image_f_724b6f_idx",
                    ),
                    # IP 주소별 접근 시간 인덱스
                    models.Index(
                        fields=["ip_address", "access_time"],
                        name="labeling_im_ip_addr_2ce8fd_idx",
                    ),
                ],
            },
        ),
    ]
