# Generated by Django 5.2 on 2025-06-29 06:49
# Django 5.2에 의해 2025-06-29 06:49에 자동 생성됨

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """사용자-관리자 소통 시스템 구축 - 메시지 전송, 답변, 읽음 상태 관리"""

    dependencies = [
        ("labeling", "0004_alter_labelingresult_unique_together_imageaccesslog"),  # 이전 마이그레이션에 의존
    ]

    operations = [
        # 메시지 모델 생성 - 사용자와 관리자 간 소통 시스템
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[("global", "전역 메시지"), ("batch", "배치별 메시지")],  # 메시지 유형 선택지
                        max_length=10,
                    ),  # 메시지 유형 (전역/배치별)
                ),
                ("subject", models.CharField(max_length=200)),  # 메시지 제목
                ("content", models.TextField()),  # 메시지 내용
                ("created_at", models.DateTimeField(auto_now_add=True)),  # 생성 시간 (자동 기록)
                ("is_read", models.BooleanField(default=False)),  # 읽음 여부 (기본값: 안읽음)
                ("admin_reply", models.TextField(blank=True, null=True)),  # 관리자 답변 내용
                ("replied_at", models.DateTimeField(blank=True, null=True)),  # 답변 시간
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="labeling.batch",
                    ),  # 관련 배치 (배치별 메시지인 경우, 배치 삭제 시 메시지도 삭제)
                ),
                (
                    "replied_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replied_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),  # 답변한 관리자 (관리자 삭제 시 답변자 정보는 NULL로 설정)
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),  # 메시지 발신자 (사용자 삭제 시 메시지도 삭제)
                ),
            ],
            options={
                "ordering": ["-created_at"],  # 생성 시간 역순으로 정렬 (최신순)
                "indexes": [
                    # 발신자별 생성 시간 인덱스
                    models.Index(
                        fields=["sender", "created_at"],
                        name="labeling_me_sender__0b35b3_idx",
                    ),
                    # 메시지 유형별 생성 시간 인덱스
                    models.Index(
                        fields=["message_type", "created_at"],
                        name="labeling_me_message_5775f8_idx",
                    ),
                    # 읽음 상태별 생성 시간 인덱스
                    models.Index(
                        fields=["is_read", "created_at"],
                        name="labeling_me_is_read_460fb2_idx",
                    ),
                ],
            },
        ),
    ]
