# Generated by Django 5.2 on 2025-06-29 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labeling", "0005_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="google_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="google_picture",
            field=models.URLField(blank=True, null=True),
        ),
    ]
