# Generated by Django 5.2 on 2025-06-29 12:47
# Django 5.2에 의해 2025-06-29 12:47에 자동 생성됨

from django.db import migrations, models


class Migration(migrations.Migration):
    """Google OAuth 연동 프로필 정보 추가 - 사용자 표시명 및 프로필 사진 (google_name, google_picture)"""

    dependencies = [
        ("labeling", "0005_message"),  # 이전 마이그레이션에 의존
    ]

    operations = [
        # Google 계정 이름 필드 추가
        migrations.AddField(
            model_name="user",
            name="google_name",
            field=models.CharField(blank=True, max_length=255, null=True),  # Google 계정의 표시 이름 (선택사항)
        ),
        
        # Google 프로필 사진 URL 필드 추가
        migrations.AddField(
            model_name="user",
            name="google_picture",
            field=models.URLField(blank=True, null=True),  # Google 프로필 사진 URL (선택사항)
        ),
    ]
