# Generated by Django 5.2 on 2025-07-02 07:24
# Django 5.2에 의해 2025-07-02 07:24에 자동 생성됨

from django.db import migrations, models


class Migration(migrations.Migration):
    """데이터베이스 성능 최적화 - 배치, 이미지, 라벨링 결과 조회 속도 향상을 위한 인덱스 추가"""

    dependencies = [
        ("labeling", "0006_user_google_name_user_google_picture"),  # 이전 마이그레이션에 의존
    ]

    operations = [
        # Batch 모델 인덱스 추가
        migrations.AddIndex(
            model_name="batch",
            index=models.Index(
                fields=["is_active", "created_at"],  # 활성 상태와 생성 시간으로 복합 인덱스
                name="labeling_ba_is_acti_627d62_idx",
            ),  # 활성 배치를 생성 시간순으로 빠르게 조회
        ),
        migrations.AddIndex(
            model_name="batch",
            index=models.Index(fields=["name"], name="labeling_ba_name_3266ac_idx"),  # 배치 이름으로 빠른 검색
        ),
        
        # Image 모델 인덱스 추가
        migrations.AddIndex(
            model_name="image",
            index=models.Index(
                fields=["batch", "file_name"], name="labeling_im_batch_i_a60f4c_idx"  # 배치와 파일명으로 복합 인덱스
            ),  # 특정 배치의 이미지를 파일명순으로 빠르게 조회
        ),
        migrations.AddIndex(
            model_name="image",
            index=models.Index(
                fields=["drive_file_id"], name="labeling_im_drive_f_535905_idx"  # Google Drive 파일 ID로 인덱스
            ),  # Google Drive 파일 ID로 빠른 검색
        ),
        
        # Label 모델 인덱스 추가
        migrations.AddIndex(
            model_name="label",
            index=models.Index(fields=["name"], name="labeling_la_name_88722d_idx"),  # 라벨 이름으로 빠른 검색
        ),
        
        # LabelingResult 모델 인덱스 추가
        migrations.AddIndex(
            model_name="labelingresult",
            index=models.Index(
                fields=["user", "image"], name="labeling_la_user_id_324ed6_idx"  # 사용자와 이미지로 복합 인덱스
            ),  # 특정 사용자의 특정 이미지 라벨링 결과를 빠르게 조회
        ),
        migrations.AddIndex(
            model_name="labelingresult",
            index=models.Index(
                fields=["created_at"], name="labeling_la_created_1255ee_idx"  # 생성 시간으로 인덱스
            ),  # 생성 시간순으로 라벨링 결과를 빠르게 조회
        ),
        migrations.AddIndex(
            model_name="labelingresult",
            index=models.Index(
                fields=["updated_at"], name="labeling_la_updated_ffa3bc_idx"  # 수정 시간으로 인덱스
            ),  # 수정 시간순으로 라벨링 결과를 빠르게 조회
        ),
    ]
