# Generated by Django 5.2 on 2025-07-03 14:55

from django.db import migrations


class Migration(migrations.Migration):
    """IAM 서비스 계정 방식으로 전환 - Google OAuth 관련 필드 제거 (google_id, google_name, google_picture)"""

    dependencies = [
        ("labeling", "0007_batch_labeling_ba_is_acti_627d62_idx_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="google_id",
        ),
        migrations.RemoveField(
            model_name="user",
            name="google_name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="google_picture",
        ),
    ]
